USE VOID_DEV;

CREATE TABLE IF NOT EXISTS SCRIPTS (
	ID INTEGER AUTO_INCREMENT,
    SCRIPT_NAME VARCHAR(50),
    CONSTRAINT PK_SCRIPTS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS EXECUTION_LOG (
	SCRIPT_ID INTEGER,
    EXECUTION_TIME DATETIME,
	CONSTRAINT FK_EXECUTION_LOG_SCRIPT_ID FOREIGN KEY (SCRIPT_ID) REFERENCES SCRIPTS (ID)
);

CREATE TABLE IF NOT EXISTS QUORA_ACCOUNTS (
	ID INTEGER AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(50) NOT NULL,
    QUORA_PASSWORD VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE,
    PHONE_NUMBER VARCHAR(15),
    LINK VARCHAR(200) NOT NULL,
    CONSTRAINT PK_QUORA_ACCOUNTS PRIMARY KEY (ID)
);

INSERT INTO QUORA_ACCOUNTS (ID, FIRST_NAME, LAST_NAME, EMAIL, QUORA_PASSWORD, LINK) VALUES ('999', 'Misc', 'Account', 'unavailable', 'unavailable', 'unavailable');


CREATE TABLE IF NOT EXISTS QUORA_QUESTION_ACCOUNT_ACTIONS (
	ID INTEGER AUTO_INCREMENT,
    ACTION_NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_QQAS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS QUORA_QUESTION_ACCOUNT_DETAILS (
	QUESTION_ID INTEGER,
    QUORA_ACCOUNT_ID INTEGER,
    ACTION_ID INTEGER,
    CONSTRAINT FK_QQAD_QUESTION_ID FOREIGN KEY (QUESTION_ID) REFERENCES QUORA_QUESTIONS(ID),
    CONSTRAINT FK_QQAD_QA_ID FOREIGN KEY (QUORA_ACCOUNT_ID) REFERENCES QUORA_ACCOUNTS(ID),
    CONSTRAINT FK_QQAD_ACTION_ID FOREIGN KEY (ACTION_ID) REFERENCES QUORA_QUESTION_ACCOUNT_ACTIONS(ID),
    CONSTRAINT PK_QQAD PRIMARY KEY (QUESTION_ID, QUORA_ACCOUNT_ID, ACTION_ID)
);

INSERT INTO QUORA_QUESTION_ACCOUNT_ACTIONS(ACTION_NAME) VALUES ('ANSWERED'), ('ASKED'), ('ASSIGNED'), ('EVALUATED'), ('REQUESTED');

INSERT INTO SCRIPTS (SCRIPT_NAME) VALUES ('Refresh_Quora_Accounts_Data'), ('Fill_Quora_Question_Dates');

CREATE TABLE IF NOT EXISTS QUORA_ASKED_QUESTIONS_STATS (
	QUESTION_ID INTEGER,
    RECORDED_ON DATE,
    VIEW_COUNT INTEGER DEFAULT 0 NOT NULL,
    FOLLOWER_COUNT INTEGER DEFAULT 0 NOT NULL,
    ANSWER_COUNT INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_QAQS_QUESTION_ID FOREIGN KEY (QUESTION_ID) REFERENCES QUORA_QUESTIONS(ID),
    CONSTRAINT PK_QAQS PRIMARY KEY (QUESTION_ID, RECORDED_ON)
);

CREATE TABLE IF NOT EXISTS QUORA_ACCOUNT_STATS (
	ACCOUNT_ID INTEGER,
    RECORDED_ON DATE,
    VIEW_COUNT INTEGER DEFAULT 0 NOT NULL,
    UPVOTE_COUNT INTEGER DEFAULT 0 NOT NULL,
    SHARE_COUNT INTEGER DEFAULT 0 NOT NULL,
    TOTAL_FOLLOWERS INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_QAS_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES QUORA_ACCOUNTS(ID),
    CONSTRAINT PK_QAS PRIMARY KEY (ACCOUNT_ID, RECORDED_ON)
);