USE VOID_DEV;

DELIMITER //

DROP PROCEDURE IF EXISTS REFRESH_QUESTIONS_TABLE;
CREATE PROCEDURE REFRESH_QUESTIONS_TABLE()

BEGIN

	DECLARE MIN_QUESTION_ID, TOTAL_QUESTIONS INT DEFAULT 0;
	SELECT MIN(ID) INTO MIN_QUESTION_ID FROM QUORA_QUESTIONS;
    SELECT COUNT(ID) INTO TOTAL_QUESTIONS FROM QUORA_QUESTIONS;
    
    IF MIN_QUESTION_ID > TOTAL_QUESTIONS THEN
    
		DROP TABLE IF EXISTS TEMP_QUORA_QUESTIONS;
		CREATE TABLE TEMP_QUORA_QUESTIONS (
			ID INTEGER AUTO_INCREMENT NOT NULL,
			OLD_ID INTEGER,
			QUESTION_URL VARCHAR(500) NOT NULL,
			QUESTION_TEXT VARCHAR(400),
			DIVISION INTEGER NOT NULL,
			ASKED_ON DATE,
			DISREGARD BOOLEAN DEFAULT FALSE,
            CONSTRAINT PK_TEMP_Q_Q PRIMARY KEY (ID)
		);
        
        INSERT INTO TEMP_QUORA_QUESTIONS (OLD_ID, QUESTION_URL, QUESTION_TEXT, DIVISION, ASKED_ON, DISREGARD)
			SELECT Q.ID, Q.QUESTION_URL, Q.QUESTION_TEXT, Q.DIVISION, Q.ASKED_ON, Q.DISREGARD
			FROM QUORA_QUESTIONS Q;
            
		INSERT INTO QUORA_QUESTIONS (ID, QUESTION_URL, QUESTION_TEXT, DIVISION, ASKED_ON, DISREGARD)
			SELECT T.ID, SUBSTRING(T.QUESTION_URL, 6), T.QUESTION_TEXT, T.DIVISION, T.ASKED_ON, T.DISREGARD
            FROM TEMP_QUORA_QUESTIONS T;
            
		INSERT INTO QUORA_QUESTION_ACCOUNT_DETAILS (QUESTION_ID, QUORA_ACCOUNT_ID, ACTION_ID)
			SELECT TQQ.ID, QQAD.QUORA_ACCOUNT_ID, QQAD.ACTION_ID
            FROM QUORA_QUESTION_ACCOUNT_DETAILS QQAD
            LEFT JOIN TEMP_QUORA_QUESTIONS TQQ
            ON TQQ.OLD_ID = QQAD.QUESTION_ID;
		
		DELETE FROM QUORA_QUESTION_ACCOUNT_DETAILS WHERE QUESTION_ID >= MIN_QUESTION_ID;
		DELETE FROM QUORA_QUESTIONS WHERE ID >= MIN_QUESTION_ID;
		ALTER TABLE QUORA_QUESTIONS AUTO_INCREMENT = 0;
        UPDATE QUORA_QUESTIONS SET QUESTION_URL = CONCAT('https', QUESTION_URL) WHERE ID < MIN_QUESTION_ID;
		DROP TABLE IF EXISTS TEMP_QUORA_QUESTIONS;
		UPDATE EXECUTION_LOG SET EXECUTION_TIME = NOW() WHERE SCRIPT_ID IN (
			SELECT ID FROM SCRIPTS WHERE SCRIPT_NAME = 'Refresh_Quora_Questions_Table'
		);

	END IF;
    
    COMMIT;
END //

DELIMITER ;